### ISSUE TITLE
Undefined method 'new' for Slack:Module

### ISSUE THREAD

**Issue by mknarciso** [ginjo/omniauth-slack#6]
Hi @ginjo !

Trying to change 'omniauth-slack' for 'ginjo-omniauth-slack' on the Gemfile gives me this error when I run the server:
```
/usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-5.1.2/lib/action_dispatch/middleware/stack.rb:35:in `build': undefined method `new' for Slack:Module (NoMethodError)
        from /usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-5.1.2/lib/action_dispatch/middleware/stack.rb:99:in `block in build'
        from /usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-5.1.2/lib/action_dispatch/middleware/stack.rb:99:in `each'
        from /usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-5.1.2/lib/action_dispatch/middleware/stack.rb:99:in `inject'
        from /usr/local/rvm/gems/ruby-2.3.4/gems/actionpack-5.1.2/lib/action_dispatch/middleware/stack.rb:99:in `build'
...
```
Using:
```
Rails 5.1.2
Puma 3.9.1
Ruby 2.3.4
```

Any advice on debbuging this?

**Comment by ginjo** [comment]
Hi @mknarciso , Just at a glance, it looks like ```.new``` is being called on ```OmniAuth::Slack```, which is a module and doesn't have a ```.new``` method. If you could post some more info - stack trace, Gemfile, OmniAuth configuration block - I could get a better idea of what's going on. What version of ginjo-onmiauth-slack are you using?

**Comment by aguynamedben** [comment]
I'm also seeing this when trying to switch to this fork. It seems as if the config:
```
provider :slack, 'API_KEY', 'API_SECRET', scope: 'string-of-scopes'
```
is being called in my app, but the Slack module is not accessible by `OmniAuth::Strategy:Slack`. The Slack strategy isn't being added to `OmniAuth.strategies` when I inspect it in `bundle exec rails c`.

I have a bunch of OmniAuth strategies setup in my config/initializers/omniauth.rb, and I'm calling `provider` with:
```rb
    provider(provider_config[:omniauth_strategy_name], *provider_config[:omniauth_args])
```

For Slack, `provider_config` is
```rb
    "slack" => {
      display_name: "Slack",
      omniauth_strategy_name: "slack", # I've tried a symbol here too
      omniauth_args: [
        ENV["SLACK_CLIENT_ID"], ENV["SLACK_CLIENT_SECRET"],
        scope: "files:read users:read users:read.email team:read identify"
      ],
    },
```

I've added `puts` around my initialization, and I'm positive `provider` is being called with `:slack`, but it's simply not added to `OmniAuth.strategies` for some reason.

omniauth 1.8.1
ginjo-omniauth-slack 2.4.1
omniauth-oauth 1.1.0
omniauth-oauth2 1.5.0
rails 5.1.6
ruby 2.3.3

I guess I will look at upgrading the omniauth version?

BTW, thank you for creating as fork of this library for the community to rally behind. It's a shame the other one was abandoned.

**Comment by ginjo** [comment]
Hi @aguynamedben , thanks for the info. Maybe it's a load-order issue somewhere in the library... I'll dig into the code and see what I can find.

**Comment by aguynamedben** [comment]
Thanks for looking into this. I'm pretty sure our `provider` call is correct.

Candidly I don't have time to dig into this right now. We pinned the repo to:
```# TODO: Use this fork: gem "ginjo-omniauth-slack"
# https://github.com/kmrshntr/omniauth-slack/issues/63
# For now, use master as of 2018-12-07, for omniauth-oauth2 version
gem "omniauth-slack", github: "kmrshntr/omniauth-slack", ref: "afd9f5c"```

In the future I will try switching to your fork and let you know if this pops up again.

**Comment by talecK** [comment]
hey @aguynamedben - just a quick sanity check, are you including the gem as follows in your gemfile?
`gem 'ginjo-omniauth-slack', require: 'omniauth-slack' `

I was banging my head against the exact same error until I realized I forgot the 'require' :(

**Comment by aguynamedben** [comment]
@talecK I have not tried that, but will at some point soon... thanks so much!
